# Generated by Django 2.2.14 on 2020-07-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testabc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hjgjh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjhgjh', models.SmallIntegerField()),
            ],
        ),
    ]
