# Generated by Django 2.2.14 on 2020-07-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hgffjhfjhg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tjhgjhgfjhg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhkjhkjhk', models.BigIntegerField()),
            ],
        ),
    ]
