# Generated by Django 2.2.14 on 2020-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tjhgjhgfjhg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='ghhfhfhg',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
